name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check code formatting
        run: npx prettier --check .
        
      - name: Run ESLint
        run: npm run lint
        
  deploy:
    needs: code-quality
    uses: ./.github/workflows/deploy.yml